<?php

return [
    'lan' => [
        "es-mx" => "Español (Mexico)",
        "es-es" => "Español (Spain)",
        "en-au" => "Inglés (Australia)",
        "en-ca" => "Inglés (Canada)",
        "en-gb" => "Inglés (Great Britain)",
        "en-in" => "Inglés (India)",
        "en-us" => "Inglés (United States)",
        "fr-ca" => "Francés (Canada)",
        "fr-fr" => "Francés (France)",
        "zh-cn" => "Chino (China)",
        "zh-hk" => "Chino (Hong Kong)",
        "zh-tw" => "Chino (Taiwan)",
        "pt-br" => "Portugués (Brazil)",
        "pt-pt" => "Portugués (Portugal)",
        "ru-ru" => "Ruso",
        "ca-es" => "Catalan",
        "da-dk" => "Danés",
        "nl-nl" => "Dutch",
        "fi-fi" => "Holandés",
        "de-de" => "Alemán",
        "it-it" => "Italiano",
        "ja-jp" => "Japonés",
        "ko-kr" => "Coreano",
        "nb-no" => "Noruego",
        "pl-pl" => "Polaco",
        "sv-se" => "Sueco (Sweden)",
    ],
];
